sudo: required

language: generic

service: docker

before_install:
  - docker build -t ix:builder environment/
  - docker run -itd --name builder -p 53001:53001 ix:builder
  - docker cp `pwd` builder:/root/dev/stack

script:
  - docker exec builder /bin/sh -c "cd stack/ix/; stack test --allow-different-user;"
